"""
Bulk migration workflow: clone repos, scan, track status, and send PRs.

Subcommands:
    prepare  - Clone flagged repos, create branches, scan, produce report
    status   - Show migration status of all prepared repos
    send-prs - Create PRs for migrated repos (all, selected, or interactive)

Prerequisites:
    gh CLI installed and authenticated (gh auth login)

Usage:
    python tools/bulk_migrate.py prepare --org YOUR_ORG
    python tools/bulk_migrate.py prepare --org YOUR_ORG --language python --workdir /tmp/migrations
    python tools/bulk_migrate.py status --workdir /tmp/migrations
    python tools/bulk_migrate.py send-prs --workdir /tmp/migrations
    python tools/bulk_migrate.py send-prs --workdir /tmp/migrations --repos repo1,repo2
    python tools/bulk_migrate.py send-prs --workdir /tmp/migrations --exclude repo3
"""

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

BRANCH_NAME = "azure-openai-to-responses-api"
PR_TITLE = "Migrate from Chat Completions to Responses API"
PR_BODY = """## What this PR does

Migrates this app from Azure OpenAI Chat Completions to the Responses API.

### Changes
- `AzureOpenAI`/`AsyncAzureOpenAI` → `OpenAI`/`AsyncOpenAI` with `base_url`
- `chat.completions.create(messages=...)` → `responses.create(input=...)`
- `choices[0].message.content` → `resp.output_text`
- Test infrastructure updated (mocks, snapshots, assertions)
- Removed `api_version` / `AZURE_OPENAI_API_VERSION` from env vars and infra

### Why
GPT-5 and newer models require the Responses API. The `/openai/v1/` endpoint is stable and requires no `api_version` management.

### How to verify
```bash
pip install openai>=1.108.1 azure-identity
pytest
```

---
*Generated by [azure-openai-to-responses](https://github.com/YOUR_ORG/azure-openai-to-responses)*
"""

SEARCH_PATTERNS = [
    "chat.completions.create",
    "AzureOpenAI(",
    "AsyncAzureOpenAI(",
    "choices[0].message.content",
]
SEARCH_RATE_LIMIT_PAUSE = 7


def gh_run(args: list[str], cwd: str | Path | None = None) -> subprocess.CompletedProcess:
    """Run a gh CLI command. Returns CompletedProcess."""
    return subprocess.run(
        ["gh"] + args,
        capture_output=True, text=True, timeout=120, cwd=cwd,
    )


def git_run(args: list[str], cwd: str | Path) -> subprocess.CompletedProcess:
    """Run a git command in a specific directory."""
    return subprocess.run(
        ["git"] + args,
        capture_output=True, text=True, timeout=60, cwd=cwd,
    )


def discover_repos(org: str, language: str | None) -> list[str]:
    """Find repos in an org that have legacy patterns. Returns list of full repo names."""
    repos: set[str] = set()

    for pattern in SEARCH_PATTERNS:
        cmd = ["search", "code", "--owner", org, pattern, "--json", "repository", "--limit", "100"]
        if language:
            cmd.extend(["--language", language])

        result = gh_run(cmd)
        if result.returncode == 0 and result.stdout.strip():
            for item in json.loads(result.stdout):
                repos.add(item["repository"]["fullName"])

        print(f"  Searched: {pattern!r} — {len(repos)} repos so far", file=sys.stderr)
        time.sleep(SEARCH_RATE_LIMIT_PAUSE)

    return sorted(repos)


def clone_repo(repo_full_name: str, workdir: Path) -> Path:
    """Clone a repo into workdir. Returns the repo directory path."""
    repo_short = repo_full_name.split("/")[-1]
    dest = workdir / repo_short

    if dest.exists():
        print(f"  Already cloned: {repo_short}", file=sys.stderr)
        return dest

    result = gh_run(["repo", "clone", repo_full_name, str(dest), "--", "--depth", "1"])
    if result.returncode != 0:
        raise RuntimeError(f"Failed to clone {repo_full_name}: {result.stderr.strip()}")

    return dest


def create_branch(repo_dir: Path) -> None:
    """Create and checkout the migration branch."""
    result = git_run(["checkout", "-b", BRANCH_NAME], cwd=repo_dir)
    if result.returncode != 0:
        # Branch might already exist
        git_run(["checkout", BRANCH_NAME], cwd=repo_dir)


def scan_repo(repo_dir: Path, scanner_path: Path) -> dict:
    """Run the legacy scanner on a repo. Returns scan results."""
    result = subprocess.run(
        [sys.executable, str(scanner_path), str(repo_dir)],
        capture_output=True, text=True, timeout=120,
    )
    return {
        "exit_code": result.returncode,
        "output": result.stdout,
        "clean": result.returncode == 0,
    }


def get_changed_files(repo_dir: Path) -> list[str]:
    """Get list of files changed relative to the default branch."""
    # Get changed tracked files (staged + unstaged)
    staged = git_run(["diff", "--cached", "--name-only"], cwd=repo_dir)
    unstaged = git_run(["diff", "--name-only"], cwd=repo_dir)
    untracked = git_run(["ls-files", "--others", "--exclude-standard"], cwd=repo_dir)

    files: set[str] = set()
    for r in [staged, unstaged, untracked]:
        if r.returncode == 0:
            files.update(f.strip() for f in r.stdout.splitlines() if f.strip())
    return sorted(files)


def load_manifest(workdir: Path) -> dict:
    """Load the bulk migration manifest."""
    manifest_path = workdir / "manifest.json"
    if manifest_path.exists():
        return json.loads(manifest_path.read_text(encoding="utf-8"))
    return {"repos": {}}


def save_manifest(workdir: Path, manifest: dict) -> None:
    """Save the bulk migration manifest."""
    manifest_path = workdir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")


# ---------------------------------------------------------------------------
# prepare — clone repos, create branches, scan, produce report
# ---------------------------------------------------------------------------

def cmd_prepare(args: argparse.Namespace) -> int:
    """Clone flagged repos, create branches, scan, produce a consolidated report."""
    workdir = Path(args.workdir).resolve()
    workdir.mkdir(parents=True, exist_ok=True)

    scanner = Path(__file__).resolve().parent.parent / ".github" / "skills" / "azure-openai-to-responses" / "scripts" / "detect_legacy.py"
    if not scanner.exists():
        print(f"Error: scanner not found at {scanner}", file=sys.stderr)
        return 1

    # Verify gh auth
    auth = gh_run(["api", "/user", "--jq", ".login"])
    if auth.returncode != 0:
        print("Error: gh CLI not authenticated. Run 'gh auth login' first.", file=sys.stderr)
        return 1
    print(f"Authenticated as: {auth.stdout.strip()}", file=sys.stderr)

    # Discover repos
    print(f"\nDiscovering repos in '{args.org}' with legacy patterns...", file=sys.stderr)
    repos = discover_repos(args.org, args.language)
    if not repos:
        print("No repos with legacy patterns found.", file=sys.stderr)
        return 0

    print(f"\nFound {len(repos)} repos. Cloning and scanning...\n", file=sys.stderr)

    manifest = load_manifest(workdir)
    manifest["org"] = args.org
    manifest["language"] = args.language
    manifest["workdir"] = str(workdir)

    for repo_full in repos:
        repo_short = repo_full.split("/")[-1]
        print(f"--- {repo_full} ---", file=sys.stderr)

        try:
            repo_dir = clone_repo(repo_full, workdir)
            create_branch(repo_dir)
            scan = scan_repo(repo_dir, scanner)

            manifest["repos"][repo_short] = {
                "full_name": repo_full,
                "path": str(repo_dir),
                "scan_hits": not scan["clean"],
                "scan_output": scan["output"],
                "status": "scanned",
                "files_changed": [],
                "pr_url": None,
            }
        except Exception as e:
            print(f"  Error: {e}", file=sys.stderr)
            manifest["repos"][repo_short] = {
                "full_name": repo_full,
                "path": None,
                "scan_hits": None,
                "scan_output": str(e),
                "status": "error",
                "files_changed": [],
                "pr_url": None,
            }

    save_manifest(workdir, manifest)

    # Print report
    print_report(manifest)

    print(f"\nManifest saved: {workdir / 'manifest.json'}")
    print(f"\nNext steps:")
    print(f"  1. Migrate each repo (use the agent or SKILL.md)")
    print(f"  2. Check status:  python migrate.py bulk status --workdir {workdir}")
    print(f"  3. Send PRs:      python migrate.py bulk send-prs --workdir {workdir}")
    return 0


# ---------------------------------------------------------------------------
# status — show migration status of all prepared repos
# ---------------------------------------------------------------------------

def cmd_status(args: argparse.Namespace) -> int:
    """Show migration status with files changed per repo."""
    workdir = Path(args.workdir).resolve()
    manifest = load_manifest(workdir)

    if not manifest.get("repos"):
        print("No repos found. Run 'bulk prepare' first.", file=sys.stderr)
        return 1

    scanner = Path(__file__).resolve().parent.parent / ".github" / "skills" / "azure-openai-to-responses" / "scripts" / "detect_legacy.py"

    for repo_short, info in manifest["repos"].items():
        if info.get("status") == "error" or not info.get("path"):
            continue

        repo_dir = Path(info["path"])
        if not repo_dir.exists():
            info["status"] = "missing"
            continue

        # Re-scan to check if migration is done
        if scanner.exists():
            scan = scan_repo(repo_dir, scanner)
            info["scan_hits"] = not scan["clean"]

        # Check for changes
        changed = get_changed_files(repo_dir)
        info["files_changed"] = changed

        if info.get("pr_url"):
            info["status"] = "pr-sent"
        elif changed and not info.get("scan_hits"):
            info["status"] = "ready"
        elif changed:
            info["status"] = "in-progress"
        else:
            info["status"] = "scanned"

    save_manifest(workdir, manifest)
    print_report(manifest)
    return 0


# ---------------------------------------------------------------------------
# send-prs — create PRs for migrated repos
# ---------------------------------------------------------------------------

def cmd_send_prs(args: argparse.Namespace) -> int:
    """Create PRs for migrated repos. Supports --repos, --exclude, or interactive."""
    workdir = Path(args.workdir).resolve()
    manifest = load_manifest(workdir)

    if not manifest.get("repos"):
        print("No repos found. Run 'bulk prepare' first.", file=sys.stderr)
        return 1

    # Determine which repos to include
    include = set(args.repos.split(",")) if args.repos else None
    exclude = set(args.exclude.split(",")) if args.exclude else set()

    candidates = []
    for repo_short, info in manifest["repos"].items():
        if info.get("status") in ("error", "missing", "pr-sent"):
            continue
        if not info.get("path"):
            continue
        repo_dir = Path(info["path"])
        changed = get_changed_files(repo_dir)
        if not changed:
            continue
        if include and repo_short not in include:
            continue
        if repo_short in exclude:
            continue
        candidates.append((repo_short, info, changed))

    if not candidates:
        print("No repos ready for PRs.", file=sys.stderr)
        return 0

    # Show what we're about to do
    print(f"\n{'Repo':<40} {'Files changed':<15} {'Status'}")
    print("-" * 70)
    for repo_short, info, changed in candidates:
        print(f"  {repo_short:<38} {len(changed):<15} {info.get('status', '?')}")
    print()

    if not args.yes:
        answer = input(f"Send PRs for {len(candidates)} repo(s)? [y/N/one-by-one] ").strip().lower()
        if answer == "one-by-one":
            filtered = []
            for repo_short, info, changed in candidates:
                a = input(f"  Send PR for {repo_short} ({len(changed)} files)? [y/N] ").strip().lower()
                if a in ("y", "yes"):
                    filtered.append((repo_short, info, changed))
            candidates = filtered
        elif answer not in ("y", "yes"):
            print("Aborted.")
            return 0

    # Send PRs
    sent = 0
    failed = 0
    for repo_short, info, changed in candidates:
        repo_dir = Path(info["path"])
        repo_full = info["full_name"]
        print(f"\n--- {repo_full} ---")

        # Stage, commit, push
        git_run(["add", "-A"], cwd=repo_dir)
        commit_msg = "Migrate from Chat Completions to Responses API"
        git_run(["commit", "-m", commit_msg], cwd=repo_dir)

        push = git_run(["push", "-u", "origin", BRANCH_NAME], cwd=repo_dir)
        if push.returncode != 0:
            print(f"  Push failed: {push.stderr.strip()}")
            failed += 1
            continue

        # Create PR
        pr_result = gh_run(
            ["pr", "create",
             "--title", PR_TITLE,
             "--body", PR_BODY,
             "--head", BRANCH_NAME],
            cwd=repo_dir,
        )
        if pr_result.returncode == 0:
            pr_url = pr_result.stdout.strip()
            print(f"  PR created: {pr_url}")
            info["pr_url"] = pr_url
            info["status"] = "pr-sent"
            sent += 1
        else:
            print(f"  PR failed: {pr_result.stderr.strip()}")
            failed += 1

    save_manifest(workdir, manifest)

    print(f"\nDone: {sent} PR(s) sent, {failed} failed.")
    if sent > 0:
        print("\nAll PR URLs:")
        for _, info, _ in candidates:
            if info.get("pr_url"):
                print(f"  {info['pr_url']}")

    return 1 if failed > 0 else 0


# ---------------------------------------------------------------------------
# Report printer
# ---------------------------------------------------------------------------

STATUS_LABELS = {
    "scanned": "Scanned (needs migration)",
    "in-progress": "In progress (has changes, still has legacy hits)",
    "ready": "Ready to PR (migrated, scanner clean)",
    "pr-sent": "PR sent",
    "error": "Error",
    "missing": "Directory missing",
}


def print_report(manifest: dict) -> None:
    """Print a formatted report of all repos."""
    repos = manifest.get("repos", {})
    if not repos:
        print("No repos in manifest.")
        return

    org = manifest.get("org", "?")
    print(f"\n{'='*72}")
    print(f"  Bulk Migration Report — {org}")
    print(f"{'='*72}\n")

    # Group by status
    by_status: dict[str, list] = {}
    for repo_short, info in repos.items():
        status = info.get("status", "unknown")
        by_status.setdefault(status, []).append((repo_short, info))

    # Summary
    print(f"  Total repos: {len(repos)}")
    for status, items in sorted(by_status.items()):
        label = STATUS_LABELS.get(status, status)
        print(f"    {label}: {len(items)}")
    print()

    # Detail table
    print(f"  {'Repo':<35} {'Status':<15} {'Files changed':<15} {'PR'}")
    print(f"  {'-'*35} {'-'*15} {'-'*15} {'-'*30}")

    for repo_short, info in sorted(repos.items()):
        status = info.get("status", "?")
        changed = info.get("files_changed", [])
        pr = info.get("pr_url") or "-"
        n_changed = str(len(changed)) if changed else "-"
        print(f"  {repo_short:<35} {status:<15} {n_changed:<15} {pr}")

    # Show files changed per repo (for repos that have changes)
    repos_with_changes = [(r, i) for r, i in repos.items() if i.get("files_changed")]
    if repos_with_changes:
        print(f"\n  --- Files changed per repo ---\n")
        for repo_short, info in sorted(repos_with_changes):
            print(f"  {repo_short}:")
            for f in info["files_changed"][:20]:
                print(f"    - {f}")
            if len(info["files_changed"]) > 20:
                print(f"    ... and {len(info['files_changed']) - 20} more")
            print()

    print(f"{'='*72}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        prog="bulk-migrate",
        description="Bulk migration workflow: clone, scan, track, and send PRs across repos",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # prepare
    p_prep = sub.add_parser("prepare", help="Clone repos, create branches, scan, produce report")
    p_prep.add_argument("--org", required=True, help="GitHub organization name")
    p_prep.add_argument("--language", help="Filter by language (e.g., python)")
    p_prep.add_argument("--workdir", default="./bulk-migrations", help="Working directory for cloned repos (default: ./bulk-migrations)")
    p_prep.set_defaults(func=cmd_prepare)

    # status
    p_status = sub.add_parser("status", help="Show migration status of all prepared repos")
    p_status.add_argument("--workdir", default="./bulk-migrations", help="Working directory")
    p_status.set_defaults(func=cmd_status)

    # send-prs
    p_pr = sub.add_parser("send-prs", help="Create PRs for migrated repos")
    p_pr.add_argument("--workdir", default="./bulk-migrations", help="Working directory")
    p_pr.add_argument("--repos", help="Comma-separated repo names to include (default: all ready)")
    p_pr.add_argument("--exclude", help="Comma-separated repo names to exclude")
    p_pr.add_argument("--yes", action="store_true", help="Skip confirmation prompt")
    p_pr.set_defaults(func=cmd_send_prs)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
